# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            lqb2writes
tagline:          'where i write'
description:      'everything changes.'
url:              http://lqb2.github.com/blog
baseurl:          /blog/

author:
  name:           'Lawrence Barriner II'
  url:            https://twitter.com/lqb2

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lqb2/blog

# Google services
google_analytics: UA-86130890-4

  
plugins: [jekyll-paginate, jekyll-feed]