# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            lqb2writes
tagline:          'where i write'
description:      'blog is transition from lqb2writes.tumblr.com. sorry about the broken links.'
url:              http://lqb2.github.com/blog
baseurl:          /blog/

author:
  name:           'Lawrence Barriner II'
  url:            https://twitter.com/lqb2

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lqb2/blog


  
gems: [jekyll-paginate]